version: '3.7'

networks: 
  rabbitmq_cluster:

services:
  rabbitmq_node_1:
    image: rabbitmq:3-management-alpine
    hostname: rmq1
    container_name: rmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
    ports:
      - 127.0.0.1:5551:15672
    networks:
      - rabbitmq_cluster

  rabbitmq_node_2:
    image: tommystark/rabbitmq-cluster:latest
    hostname: rmq2
    container_name: rmq2
    depends_on:
      - rabbitmq_node_1
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      - NODE_TO_CLUSTER_WITH=rmq1
    ports:
      - 127.0.0.1:5552:15672
    networks:
      - rabbitmq_cluster

  rabbitmq_node_3:
    image: tommystark/rabbitmq-cluster:latest
    hostname: rmq3
    container_name: rmq3
    depends_on:
      - rabbitmq_node_1
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      - NODE_TO_CLUSTER_WITH=rmq1
    ports:
      - 127.0.0.1:5553:15672
    networks:
      - rabbitmq_cluster
