version: '3.7'

networks: 
  harmq:

services:
  rabbitmq_node_1:
    image: rabbitmq:3-management-alpine
    hostname: rmq1
    container_name: rmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
    ports:
      - 127.0.0.1:5551:15672
    networks:
      - harmq

  rabbitmq_node_2:
    image: rabbitmq:3-management-alpine
    hostname: rmq2
    container_name: rmq2
    depends_on:
      - rabbitmq_node_1
    command:
      - /bin/bash
      - -c
      - |
        rabbitmq-server -detached
        rabbitmqctl stop_app
        rabbitmqctl reset
        rabbitmqctl join_cluster rabbit@rmq1
        rabbitmqctl start_app
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
    ports:
      - 127.0.0.1:5552:15672
    networks:
      - harmq

  rabbitmq_node_3:
    image: rabbitmq:3-management-alpine
    hostname: rmq3
    container_name: rmq3
    depends_on:
      - rabbitmq_node_1
    command:
      - /bin/bash
      - -c
      - |
        rabbitmq-server -detached
        rabbitmqctl stop_app
        rabbitmqctl reset
        rabbitmqctl join_cluster rabbit@rmq1
        rabbitmqctl start_app
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
    ports:
      - 127.0.0.1:5553:15672
    networks:
      - harmq
