version: '3.7'

networks:
  haOverlay:
    external: true

services:
  rabbitmq_node_2:
    image: rabbitmq:3-management-alpine
    hostname: node2
    deploy:
      replicas: 1
    entrypoint:
      - /bin/bash
      - -c
      - |
        rabbitmq-server -detached
        rabbitmqctl stop_app
        rabbitmqctl reset
        rabbitmqctl join_cluster rabbit@rmq1
        rabbitmqctl start_app
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      - RABBITMQ_NODENAME=node2
    ports:
      - target: 5671
        publish: 5671
        protocol: tcp
        mode: host
      - target: 5672
        publish: 5672
        protocol: tcp
        mode: host
      - target: 15671
        publish: 15671
        protocol: tcp
        mode: host
      - target: 15672
        publish: 15672
        protocol: tcp
        mode: host
    networks:
      haOverlay:
        aliases:
          - node2