version: '3.7'

networks:
  haOverlay:
    external: true

services:
  rabbitmq_node_3:
    image: harabbitmq:latest
    hostname: rmq3
    deploy:
      replicas: 1
    environment:
      - ERLANG_COOKIE = {$ERLANG_COOKIE}
    ports:
      - target: 5671
        publish: 5671
        protocol: tcp
        mode: host
      - target: 5672
        publish: 5672
        protocol: tcp
        mode: host
      - target: 15671
        publish: 15671
        protocol: tcp
        mode: host
      - target: 15672
        publish: 15672
        protocol: tcp
        mode: host
    networks:
      haOverlay:
        aliases:
          - rmq3