version: '3.7'

networks:
  haOverlay:
    name: haOverlay
    driver: overlay
    attachable: true

services:
  rabbitmq_node_1:
    image: harabbitmq:latest
    hostname: node1
    deploy:
      replicas: 1
    environment:
      - ERLANG_COOKIE=$ERLANG_COOKIE
      - RABBITMQ_NODENAME=node1
      - CLUSTERED=true
    ports:
      - target: 5671
        publish: 5671
        protocol: tcp
        mode: host
      - target: 5672
        publish: 5672
        protocol: tcp
        mode: host
      - target: 15671
        publish: 15671
        protocol: tcp
        mode: host
      - target: 15672
        publish: 15672
        protocol: tcp
        mode: host
    networks:
      haOverlay:
        aliases:
          - node1