version: '3.7'

networks:
  haOverlay:
    external: true

services:
  rabbitmq_node_3:
    image: rabbitmq-cluster-alpine:latest
    hostname: node3
    deploy:
      replicas: 1
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      - RABBITMQ_NODENAME=node3
      - NODE_TO_CLUSTER_WITH=node1
    ports:
      - target: 5671
        publish: 5671
        protocol: tcp
        mode: host
      - target: 5672
        publish: 5672
        protocol: tcp
        mode: host
      - target: 15671
        publish: 15671
        protocol: tcp
        mode: host
      - target: 15672
        publish: 15672
        protocol: tcp
        mode: host
    networks:
      haOverlay:
        aliases:
          - node3